### ISSUE TITLE
Parameter syntax is not consistent with RFC1738 (URL syntax)

### ISSUE THREAD

**Issue by tlau** [RobotWebTools/mjpeg_server#5]
The correct form for URLs should be `http://localhost:8080/stream?topic=/IMAGE_TOPIC&param1=value1&param2=value2&param3=value3`, not using question marks as documented for mjpeg_server.

**Comment by baalexander** [comment]
Thanks @tlau. Where's the wrong way documented?

**Comment by tlau** [comment]
Section 3.3 on http://wiki.ros.org/mjpeg_server says to use ?'s in between parameters.  I tried using the correct syntax first, but mjpeg_server doesn't recognize it; it only accepts the incorrect syntax.

**Comment by baalexander** [comment]
Thanks @tlau, I updated the wiki to use '&' between parameters. Please feel free to edit or add to the wikis as needed.

**Comment by rctoris** [comment]
@baalexander i think the problem is that mjpeg server itself looks for the wrong syntax. The wiki itself was correct for mjpeg server (although i think it's wrong now) but incorrect altogether in terms of the standard  mentioned.

**Comment by baalexander** [comment]
Ahh, gotchya, mjpeg_server itself is expecting question marks between params instead of ampersands. I reverted the wiki page back to using '?'.

**Comment by tlau** [comment]
Right, the server only accepts the wrong format.

**Comment by mitchellwills** [comment]
The new web_video_server package (http://wiki.ros.org/web_video_server) that supports mjpeg streams is consistent with RFC1738.
